### PR TITLE
fix!: use plural names for options

### PR DESCRIPTION
**Pull request by aawsome**
Consistently uses singular and plural names for options in config and CLI

BREAKING CHANGE: This requires to adapt CLI calls and config keys.

Affected options:
- `glob` -> `globs` in config profile
- `iglob` -> `iglobs` in config profile
- `glob`-file -> `glob-files` in config profile
- `iglob-file` -> `iglob-files` in config profile
- `custom-ignore-file` -> `custom-ignore-files` in config profile
- `tag`-> `tags` in config profile
- `keep-tags` -> now only array
- `keep-ids` -> now only array

### CODE REVIEW

**Comment by simonsan** [comment]
Added to https://github.com/rustic-rs/docs/pull/88

**Comment by simonsan** [comment]
Can we still add the plural for:

```toml
filter-host = ["host2"] # Default: []
filter-label = ["label1"] # Default: []
```

**Comment by aawsome** [comment]
> Can we still add the plural for:
> 
> ```toml
> filter-host = ["host2"] # Default: []
> filter-label = ["label1"] # Default: []
> ```

Yes, but this is a change in `rustic-rs`, not in `rustic_core`, see the latest commit in https://github.com/rustic-rs/rustic/pull/1240.

**Review by simonsan — APPROVED** [review]
Great, it's really consistent now! LGTM!

**Pull request merged**
