### PR TITLE
Unbreak building of rustic_core-0.1.1 on OpenBSD (#27)

### PR DESCRIPTION
**Pull request by bket**
Issue was caused by a couple of configuration checks.

### CODE REVIEW

**Comment by bket** [comment]
Forgot to mention that with this patch all tests provided by `cargo test` pass.

**Comment by bket** [comment]
@simonsan, @aawsome, clippy seems to fail at a point that has not been touched by this PR. Is this a known issue?

**Comment by aawsome** [comment]
I would say it is definitively a new Rust/Clippy version which gives these warnings - I'll work on a fix and then we can merge this PR.
Sorry for being a bit short of time ATM - day job and family are currently a bit demanding...

**Comment by aawsome** [comment]
I would say it is definitively a new Rust/Clippy version which gives these warnings - I'll work on a fix and then we can merge this PR.
Sorry for being a bit short of time ATM - day job and family are currently a bit demanding...

**Review by aawsome — APPROVED** [review]
LGTM!
Thanks a lot @bket and sorry for the inconveniences!

**Pull request merged**
